version: 0.0
os: linux

files:
  - source: ./src/service.py
    destination: /home/ec2-user/webservice/src

hooks:
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu

