version: 0.0
os: linux

files:
  - source: ./src/service.py
    destination: /home/ec2-user/webservice/src
  - source: ./src/db_operation.py
    destination: /home/ec2-user/webservice/src
  - source: ./src/s3_operation.py
    destination: /home/ec2-user/webservice/src
  - source: ./systemd/webapp.service
    destination: /etc/systemd/system/

hooks:
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ec2-user
