### Get user information
GET http://127.0.0.1:3333/v1/user/self HTTP/1.1
Authorization: Basic linqinyun@outlook.com:123456abc


### Update user information
PUT http://127.0.0.1:3333/v1/user/self HTTP/1.1
Authorization: Basic linqinyun@outlook.com:123456abc

{
    "first_name": "Qinyun_new",
    "last_name": "Lin_new_new"
}


### Simple test
GET http://127.0.0.1:3333/healthz


### Created user
POST http://127.0.0.1:3333/v1/user HTTP/1.1
content-type: application/json

{
    "first_name": "Qinyun",
    "last_name": "Lin",
    "password": "123456",
    "email_address": "linqinyun@outlook.com"
}

