# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application unit test

on:
  pull_request:
    branches: [ main ]

jobs:
  validate_python:
    runs-on: ubuntu-latest
    steps:
    # set python version
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    # Install dependencies:
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest mysql-connector-python boto3 statsd

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        pwd
        pytest
