
name: Validate Packer Syntax

on:
  pull_request:
    branches: [ main ]

jobs:
  validate_packer:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./webservice/packer/ami.json
